blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/sjelfull/craft3-templateselect/discussions/new?category=ideas
    about: Start a new discussion about your idea